### PR TITLE
Hv addprofilemapping

### PR DESCRIPTION
**Pull request by HansVRP**

### CODE REVIEW

**Comment by jdries** [comment]
@HansVRP  I ran the notebook myself, on my max ndvi example:

1.  I made small improvements based on that experience
2. The heatmap has an issue, spatial and temporal range seem to be expected in the dataframe, but weren't there in my case
3. I would avoid adding NDWI udp
4. We'll want to integrate the code perhaps with python library

Otherwise, this is a great tool, and would be good to get it merged so we can include it in documentation and SRR.

**Comment by HansVRP** [comment]
@jdries Hi Jeroen this was really a dummy example. Let's discuss the requisites for the underlying UDPs and then I can properly expand the benchmark/visualisation to cover all requirements

**Comment by jdries** [comment]
Hi @HansVRP , the goal for SRR in octobre is to have an MVP that is sufficiently visible to the reviewers. So in terms of functionality, this is already enough, we just need to increase visibility by putting it in apex docs and out of a pr.
It is fine to clearly label it as MVP/prototype, to avoid bad experiences.

If fixing the heatmap seems to complex, we can also just not use it, or show a screenshot.

**Comment by HansVRP** [comment]
@jdries should be good for review. Stepped away from the class based implementation and cleaned up the notebook to make it more explanatory

**Comment by jdries** [comment]
ok:
ndwi.json is probably not necessary anymore?

There's this issue:
https://github.com/ESA-APEx/apex_algorithms/issues/15

So not sure what to do, just merge this one and then in follow up work merge both projects and also move this code to a better location?

**Comment by HansVRP** [comment]
that sounds indeed like a good follow-up step

**Pull request merged**
